- name: Deploy FixMaster (simple)
  hosts: all
  become: yes

  vars:
    compose_project_dir: "/opt/app"
    compose_file: "docker-compose.yml"

  tasks:
    - name: Ensure compose project dir exists
      ansible.builtin.file:
        path: "{{ compose_project_dir }}"
        state: directory

    - name: Copy docker-compose.yml to server
      ansible.builtin.copy:
        src: "./docker-compose.yml"
        dest: "{{ compose_project_dir }}/{{ compose_file }}"
        mode: "0644"

    - name: Deploy new version with docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ compose_project_dir }}"
        pull: always
        build: always
        state: present
        recreate: always
        remove_orphans: true
