apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fixmaster-ingress
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: 72.56.248.210.niq.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fixmaster-service  # Имя сервиса, который мы только что создали
                port:
                  number: 80             # Порт сервиса (не контейнера!)