apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-postgres-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Данные останутся даже если удалить PVC
  storageClassName: "" # Пустой класс, чтобы совпало с PVC без класса
  hostPath:
    path: "/mnt/data/postgres" # Путь на реальной ноде worker-192.168.0.5
    type: DirectoryOrCreate   # Создать папку, если её нет
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-192.168.0.5 # Привязываем диск конкретно к этой ноде