apiVersion: v1
kind: Secret
metadata:
  name: fixmaster-secret
  namespace: default
type: Opaque

stringData:
  SECRET_KEY: "secretKey"
  FIXMASTER_CLIENT_BOT_TOKEN: "fixmasterClientBotToken"
  FIXMASTER_MASTER_BOT_TOKEN: "fixmasterMasterBotToken"
  FIXMASTER_MODERATOR_BOT_TOKEN: "fixmasterModeratorBotToken"
  FIXMASTER_ORGANIZATION_BOT_TOKEN: "fixmasterOrganizationBotToken"
  POSTGRES_HOST: "postgresHost"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgresUser"
  POSTGRES_PASSWORD: "postgresPassword"
  POSTGRES_DB: "postgresDb"