name: "CI for all branches "

on: 
  pull_request:
    branches:
      - main
      - master
      - develop

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true


jobs:
  qualtiy:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install ruff black mypy
          pip install -r requirements.txt || true

      - name: Ruff lint
        run: ruff check .

      - name: Black (check format)
        run: black --check .

      - name: Mypy type check
        run: mypy ./

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run testing
        run: |
          docker compose up -d && sleep 30
          docker compose exec app python manage.py test > test-reason.txt
      
      - name: Upload test reason 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reason
          path: test-reason.txt